import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Mondly By Pearson",
  description: "Generated by create next app",
  openGraph: {
    title: "Mondly By Pearson",
    description: "Aprenda idiomas com tecnologia e inovação.",
    url: "https://parcerias.indico.net.br/itauagencias/minhasvantagens/mondly",
    siteName: "Mondly By Pearson",
    images: [
      {
        url: "/itauagencias/minhasvantagens/mondly/images/mondly-logo.png",
        width: 113,
        height: 40,
        alt: "Logo Mondly",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Mondly By Pearson",
    description: "Aprenda idiomas com tecnologia e inovação.",
    images: ["https://parcerias.indico.net.br/itauagencias/minhasvantagens/mondly"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
